# Generated by Django 5.0.7 on 2024-09-08 00:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_paymenttype_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together={('user', 'payment_type', 'detail')},
        ),
    ]
