# Generated by Django 5.0.7 on 2025-04-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0006_alter_paymentmethod_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttype",
            name="payment_class",
            field=models.CharField(
                choices=[
                    ("phone_number", "Phone Number"),
                    ("credit_card", "Credit Card"),
                    ("master_card", "Master Card"),
                ],
                default="phone_number",
                max_length=20,
                verbose_name="Payment Class",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="detail",
            field=models.JSONField(verbose_name="Detail"),
        ),
    ]
