# Generated by Django 5.0.7 on 2025-05-17 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0010_paymenttransaction_provider"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentstatus",
            options={"verbose_name_plural": "PaymentStatus"},
        ),
        migrations.AlterUniqueTogether(
            name="paymentstatus",
            unique_together=set(),
        ),
    ]
