# Generated by Django 5.0.7 on 2025-05-18 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0011_alter_paymentstatus_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                    ("refund_failed", "Refund Failed"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="paymentstatus",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="statuses",
                to="payment.paymenttransaction",
            ),
        ),
        migrations.CreateModel(
            name="PaymentRefund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "provider_refund_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "manual_refund_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("succeeded", models.BooleanField(default=False)),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund",
                        to="payment.paymenttransaction",
                    ),
                ),
            ],
        ),
    ]
