# Generated by Django 5.0.7 on 2025-05-25 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_orderstatus_status"),
        ("payment", "0012_alter_paymentstatus_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenttransaction",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment",
                to="core.order",
            ),
        ),
    ]
