# Generated by Django 5.0.7 on 2025-11-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_paymenttype_deposit_fee_fixed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='provider',
            field=models.CharField(choices=[('flutterwave', 'Flutterwave'), ('pawapay', 'Pawapay')], max_length=50),
        ),
    ]
