# Generated by Django 5.0.7 on 2026-04-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_rename_emaketa_deposit_fee_fixed_paymenttype_platform_deposit_fee_fixed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('collection', 'Collection'), ('disbursement', 'Disbursement'), ('refund', 'Refund')], default='collection', max_length=20),
        ),
    ]
