# Generated by Django 5.0.7 on 2024-08-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paymentmethod_detail_paymentmethod_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='logo',
            field=models.ImageField(null=True, upload_to='payment_logos', verbose_name='Payment Logo'),
        ),
    ]
