# Generated by Django 5.0.7 on 2024-08-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_paymenttype_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='logo',
            field=models.ImageField(upload_to='payment_logos', verbose_name='Payment Logo'),
        ),
    ]
