# Generated by Django 5.0.7 on 2024-08-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_paymenttype_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
