# Generated by Django 5.0.7 on 2025-05-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0009_alter_paymenttransaction_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="provider",
            field=models.CharField(
                choices=[("flutterwave", "Flutterwave")],
                default="flutterwave",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
