# Generated by Django 5.0.7 on 2025-06-11 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_systemconfiguration_delivery_within'),
        ('kunshort_payment', '0015_alter_paymenttransaction_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.order'),
        ),
    ]
