# Generated by Django 5.0.7 on 2025-11-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_alter_paymenttransaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='deposit_fee_fixed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='deposit_fee_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='emaketa_deposit_fee_fixed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='emaketa_deposit_fee_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
