# Generated by Django 5.0.7 on 2026-04-01 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0019_alter_paymenttransaction_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttype',
            old_name='emaketa_deposit_fee_fixed',
            new_name='platform_deposit_fee_fixed',
        ),
        migrations.RenameField(
            model_name='paymenttype',
            old_name='emaketa_deposit_fee_percentage',
            new_name='platform_deposit_fee_percentage',
        ),
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together={('user_id', 'payment_type', 'detail')},
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='order',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='user',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='user_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='coupon_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='order_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.paymenttype'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='provider',
            field=models.CharField(choices=[('flutterwave', 'Flutterwave'), ('pawapay', 'Pawapay'), ('mobile_money', 'Mobile Money'), ('orange_money', 'Orange Money'), ('mtn_money', 'MTN Money')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='user',
        ),
    ]
